### ISSUE TITLE
Support Mozilla Firefox Critical Review search plugin 

### ISSUE THREAD

**Issue by melloc** [browncr/cr-www#22]
The old site allows you to add the Critical Review as a search engine. We should make sure we continue to support this.

**Comment by constinit** [comment]
While we're at it, we can integrate the search into the Chrome:
http://stackoverflow.com/a/7630169

**Comment by melloc** [comment]
Do you want to work on these? I haven't pushed the search functionality yet, but the place to send these queries is /search?q=query.

**Comment by constinit** [comment]
Sure, I'll take a look tonight
