### ISSUE TITLE
Find examples of using Shibboleth with Play

### ISSUE THREAD

**Issue by melloc** [browncr/cr-www#9]
We'll need the site to work with CIS's Shibboleth infrastructure. Also look for examples of whitelisting IP ranges for accessing certain URLs.

**Comment by constinit** [comment]
There's a third-party module that supports shibboleth:
https://github.com/TAMULib/Shibboleth-play/tree/play2.0

Unfortunately, it hasn't been updated in three years and might not support play 2 (there's a play 2 branch that hasn't been merged into master). I'm going to clone the repo and see if it still works.

**Comment by constinit** [comment]
The play 1 shibboleth module probably needs a complete rewrite for play 2. We should stick with the port forwarding solution for now.
